---
abstract: extension of SQL::Abstract with more constructs and more flexible API
author:
  - 'Laurent Dami <laurent.dami@justice.ge.ch>'
build_requires:
  SQL::Abstract::Test: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Abstract-More
provides:
  SQL::Abstract::More:
    file: lib/SQL/Abstract/More.pm
    version: 1.05
requires:
  MRO::Compat: 0
  Params::Validate: 0
  SQL::Abstract: 1.61
  namespace::clean: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.05
