---
abstract: 'extension of SQL::Abstract with more constructs and more flexible API'
author:
  - 'Laurent Dami <laurent.dami@justice.ge.ch>'
build_requires:
  SQL::Abstract::Test: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Abstract-More
provides:
  SQL::Abstract::More:
    file: lib/SQL/Abstract/More.pm
    version: 1.16
requires:
  MRO::Compat: 0
  Params::Validate: 0
  SQL::Abstract: 1.73
  Scalar::Does: 0
  namespace::clean: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/damil/SQL-Abstract-More
version: 1.16
